spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: spring-cloud-task
logging:
  level:
    org:
      springframework:
        cloud:
          task: debug
